Story_10/urls.py
from django.urls import path
from .views import show_registration_form, validate_email, form_submission, show_subscriber, get_subscriber, unsubscribe


app_name = 'Story_10'
urlpatterns = [
    path('', show_registration_form, name='form-registrasi'),
    path('validasi-email/', validate_email, name='validate-email'),
    path('submit-form/', form_submission, name='add-subscriber'),
    path('list-subscriber/', show_subscriber, name='list-subscriber'),
    path('list-subscriber/get-subscriber/', get_subscriber, name='get-subscriber'),
    path('list-subscriber/unsubscribe/', unsubscribe, name='unsubscribe'),
]

Story_6/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import status_view, add_status, show_profile

app_name = "Story_6"
urlpatterns = [
	path('', RedirectView.as_view(url='story-6/profile/')),
	path('status/', status_view, name="status"),
	path('add-status/', add_status, name='add_status'),
    path('profile/', show_profile, name='profile'),
]

buku/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import list_buku, get_json, token_verification, clear_session

app_name = "Story_9"
urlpatterns = [
    path('', list_buku, name='buku'),
    path('get-json/<str:jenis>', get_json, name='get-json'),
    path('verifikasi', token_verification, name='verifikasi'),
	path('clear-session', clear_session, name='clear-session'),
]

newStory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

import Story_6.urls as Story_6
import buku.urls as Story_9
import Story_10.urls as Story_10

app_name = ''
urlpatterns = [
    path('admin/', admin.site.urls),
	path('', RedirectView.as_view(url='story-6/profile')),
    path('story-6/', include(Story_6, namespace='Story_6')),
    path('story-9/', include(Story_9, namespace='Story_9')),
    path('story-10/', include(Story_10, namespace='Story_10')),
]

Story_6/models.py
from django.core.validators import MaxLengthValidator
from django.db import models


class Status(models.Model):
    status = models.CharField(max_length=300,
                              validators=[MaxLengthValidator(300)])
    created_at = models.DateTimeField(auto_now_add=True)

Story_6/forms.py
from django import forms
from .models import Status


class StatusForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(StatusForm, self).__init__(*args, **kwargs)

        self.fields['status'].label = 'Status'
        self.fields['status'].widget = forms.Textarea(attrs={'class': 'form-control',
                                                             'placeholder': 'Apa yang sedang anda pikirkan?',
                                                             'rows': 5,
                                                             'cols': 8,
                                                             'style': 'resize : none'}
                                                      )
        self.fields['status'].error_messages = {'max_length': 'Batas maksimal karakter 300',
                                                'required': 'Status harus diisi'}

    class Meta:
        model = Status
        fields = ['status']

Story_6/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import StatusForm
from .models import Status

response = {}
def status_view(request):
    response['status'] = Status.objects.all()
    response['form'] = StatusForm()
    html = 'home.html'
    response['name'] = []
    if 'name' in request.session.keys():
        response['name'] = request.session['name']
    return render(request, html, response)


def add_status(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('Story_6:status'))
    else:
        form = StatusForm()
    return render(request, 'home.html', {'form': form,
                                         'status': Status.objects.all()})
def show_profile(request):
    response['name'] = []
    if 'name' in request.session.keys():
        response['name'] = request.session['name']
    return render(request, 'profile.html', response)

Story_6/templates/base.html
<!DOCTYPE html>
<html lang="en">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="google-signin-client_id" content="437567450840-bafn5o9vu84bjlli1i98k7rb2gdv2dsf.apps.googleusercontent.com">
    <title>Muhamad Lutfi Arif</title>
    {% block source %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="https://apis.google.com/js/platform.js" async defer></script>
    {% endblock source %}
<style>
    {% block style %}
        body {
            text-align: center;
            background: white;
	        background-size: cover;
            font-family: 'Dosis', sans-serif !important;
        }
        #logout {
        border-radius: 2px;
            vertical-align: middle;
            border: 1px white solid;
            background-color: white;
            margin-bottom: 10px;
            margin-top: 8px;
            margin-left: 10px;
            padding: 0px 10px;
        }
        #logout a{
            padding: 0px;
            color: #2196F3;
        }
        #loader {
            position: absolute;
            left: 50%;
            top: 50%;
            z-index: 1;
            width: 150px;
            height: 150px;
            margin: -75px 0 0 -75px;
            border: 16px solid #f3f3f3;
            border-radius: 50%;
            border-top: 16px solid #3498db;
            width: 120px;
            height: 120px;
            -webkit-animation: spin 2s linear infinite;
            animation: spin 2s linear infinite;
        }

        @-webkit-keyframes spin {
            0% { -webkit-transform: rotate(0deg); }
            100% { -webkit-transform: rotate(360deg); }
        }

        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }

        /* Add animation to "page content" */
        .animate-bottom {
            position: relative;
            -webkit-animation-name: animatebottom;
            -webkit-animation-duration: 1s;
            animation-name: animatebottom;
            animation-duration: 1s
        }

        @-webkit-keyframes animatebottom {
            from { bottom:-100px; opacity:0 }
            to { bottom:0px; opacity:1 }
        }

        @keyframes animatebottom {
            from{ bottom:-100px; opacity:0 }
            to{ bottom:0; opacity:1 }
        }

        #content-page {
            display: none;
            text-align: center;
        }

    {% endblock style %}
</style>
</head>
<body onload="myFunction()" style="margin:0;">
    <div id="loader"></div>
    {% include 'navbar.html' %}
    <div id="content-page" class="animate-bottom">
    {% block content %}
    {% endblock content %}
    </div>
</body>
    <script>
    var myVar;

    function myFunction() {
        myVar = setTimeout(showPage, 2000);
    }

    function showPage() {
      document.getElementById("loader").style.display = "none";
      document.getElementById("content-page").style.display = "block";
    }

    function onSignIn(googleUser) {
        var token = googleUser.getAuthResponse().id_token;
        $.ajax({
            url: '/story-9/verifikasi',
            method: 'POST',
            dataType: 'json',
            data: {'token': token},
            success: function (result) {
                console.log('User signed in.');
                location.reload()
            }
        });
    }

    function signOut() {
        gapi.load('auth2', function () {
            gapi.auth2.init().then(function () {
                var auth2 = gapi.auth2.getAuthInstance();
                auth2.signOut().then(function () {
                    $.ajax({
                        url: '/story-9/clear-session',
                        success: function (result) {
                            console.log('User signed out.');
                            location.reload();
                        }
                    });
                });
            });
        });
    }
    </script>
    {% block script %}
    {% endblock script %}
</html>

Story_6/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="main-div">
            <div class="jumbotron">
                <div class="container-fluid">
                    <h1 class="page-header" style="text-align: center">Hello, apa kabar?</h1>
                </div>
            </div>

            <div class="container mx-auto d-block">
                <form class="form-block" action="{% url 'Story_6:add_status' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form }}
                    </div>
                    <button name="tombol_submit" type="submit" class="btn btn-primary">Input Status</button>
                </form>
            </div>

            <div class="container mx-auto d-block" style="padding-top: 50px;">
                {% if status %}
                    <table class="table table-hover table-striped table-dark" align="center" style="text-align: center">
                        <thead>
                            <tr>
                                <th scope="col">Status</th>
                                <th scope="col">Waktu Pembuatan</th>
                            </tr>
                        </thead>
                        {% for data in status %}
                        <tr>
                            <td scope="row" id="Stats_content">{{ data.status }}</td>
                            <td scope="row">{{ data.created_at|date:"l" }}, {{ data.created_at }}</td>
                        </tr>
                    {% endfor %}
                    </table>
                {% else %}
                    <h1 class="text-main">Tidak Ada Status</h1>
                {% endif %}
            </div>
        </div>
{% endblock content %}

Story_6/templates/navbar.html
    <style>
        .navbar {
            background-color: #2196F3 !important;
            font-family: 'Dosis', sans-serif !important;
        }
        a {
            font-size: 18px;
        }
    </style>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Story_6:profile' %}">Profile <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Story_6:status' %}">Status <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Story_9:buku' %}">List Buku <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Story_10:form-registrasi' %}">Form Subscriber <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Story_10:list-subscriber' %}">List Subscriber <span class="sr-only">(current)</span></a>
                </li>
            </ul>
            {% if not name %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <div class="nav-link g-signin2" data-onsuccess="onSignIn"></div>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Welcome, {{ name }}<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <li id='logout' class="nav-item active">
                        <a class="nav-link" onclick="signOut();" href="#">Logout <span class="sr-only">(current)</span></a>
                    </li>
                </li>
            </ul>
            {% endif %}
        </div>
    </nav>

Story_6/templates/profile.html
{% extends 'base.html' %}

{% load static %}
{% block source %}
{{ block.super }}
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
	<script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/Story8.js' %}"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" type='text/css' href='{% static 'css/jquery-ui.css' %}'>
{% endblock source %}

{% block style %}
{{ block.super }}
    body {
        text-align: center;
        background: white;
	    background-size: cover;
        line-height: 1.8;
        font-family: 'Dosis', sans-serif !important;
    }
    img {
        border-radius: 100%;
        border: 10px solid #2196f3;
        box-shadow: 0 5px 5px 0 rgba(0, 0, 0, 0.5);
    }

    p {
        font-size: 18px;
        line-height: 1.8;
    }
    #footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        text-align: center;
    }
    #title {
        font-size: 50px;
        padding: 10px;
    }
    /* The switch - the box around the slider */
    .switch {
      position: relative;
      display: inline-block;
      width: 60px;
      height: 34px;
    }

    /* Hide default HTML checkbox */
    .switch input {
      opacity: 0;
      width: 0;
      height: 0;
    }

    /* The slider */
    .slider {
      position: absolute;
      cursor: pointer;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background-color: #ccc;
      -webkit-transition: .4s;
      transition: .4s;
    }

    .slider:before {
      position: absolute;
      content: "";
      height: 26px;
      width: 26px;
      left: 4px;
      bottom: 4px;
      background-color: white;
      -webkit-transition: .4s;
      transition: .4s;
    }

    input:checked + .slider {
      background-color: #2196F3;
    }

    input:focus + .slider {
      box-shadow: 0 0 1px #2196F3;
    }

    input:checked + .slider:before {
      -webkit-transform: translateX(26px);
      -ms-transform: translateX(26px);
      transform: translateX(26px);
    }

    /* Rounded sliders */
    .slider.round {
      border-radius: 34px;
    }

    .slider.round:before {
      border-radius: 50%;
    }
    #accordion h3 {
        color: white !important;
        font-size: 20px;
        font-family: 'Dosis', sans-serif !important;
        border-radius: 50px;
        background-color: rgba(33, 150, 243, 1);
        border-color:rgba(255,255,255,0);
        box-shadow: 3px 3px 3px  grey;
        margin-top:7px;
        padding-bottom: 5px;
        padding-top: 5px;
    }
    #accordion div {
        font-size: 18px;
        color: black !important;
        font-family: 'Dosis', sans-serif !important;
      border-radius: 10px;
      width:250px;
      border-color:rgba(255,255,255,0);
      background-color: rgba(33, 150, 243, 0.2);
      margin-top:7px;
      margin-bottom:-5px;
    }
{% endblock style %}
{% block content %}
    <h1 id="title" style="font-size: 50px; font-family: 'Dosis', sans-serif;">This is My Profile</h1>

    <div class="col-md-12">
        <div class="container">
            <img class="img-circle" src="https://pbs.twimg.com/media/DmdGUTyU0AAp3dU.jpg" width="160" height="160">
            <div style="margin-top: 10px">
                <label class="switch">
                <input type="checkbox" id="switch-button">
                <span class="slider round"></span>
            </label>
            </div>
            <h3>My Name is</h3>
            <h3><strong>Muhamad Lutfi Arif</strong></h3>
            <center>
                <div id="accordion" style="width: 300px">
                        <h3>My Activities</h3>
                    <div>
                        Coding<br>Eat<br>Sleep
                    </div>
                        <h3>Experience</h3>
                    <div>
                        FUKI 2018<br>SIWAK-NG 2018<br>SALAM UI 2018
                    </div>
                        <h3>Achievement</h3>
                    <div>
                        Juara 1 Rangking 1 SIWAK-NG 2018
                    </div>
                </div>
            </center>

        </div>
    </div>
    <p id="footer" style="color:#000000; font-size: 14px;">&copy; Made with Love by Muhamad Lutfi Arif </p>
    </div>
{% endblock content %}